#pragma checksum "MainWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "4A33E8491DEA1CAC9695D1CD524D221A076DF802FBABE6F61F674E7EA1955D60"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Cad_to_tekla;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Cad_to_tekla {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 8 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Cad_to_tekla.MainWindow w_mainWindow;
        
        #line default
        #line hidden
        
        
        #line 18 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button tb_ref;
        
        #line default
        #line hidden
        
        
        #line 19 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button tb_PickLines;
        
        #line default
        #line hidden
        
        
        #line 20 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button tb_modifyModel;
        
        #line default
        #line hidden
        
        
        #line 21 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button tb_pickProfile;
        
        #line default
        #line hidden
        
        
        #line 22 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cb_vl_hz;
        
        #line default
        #line hidden
        
        
        #line 27 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cm_beamAtt;
        
        #line default
        #line hidden
        
        
        #line 29 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dt_data;
        
        #line default
        #line hidden
        
        
        #line 35 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn Select;
        
        #line default
        #line hidden
        
        
        #line 58 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button tb_browesRef;
        
        #line default
        #line hidden
        
        
        #line 59 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tx_refPath;
        
        #line default
        #line hidden
        
        
        #line 60 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tx_refScale;
        
        #line default
        #line hidden
        
        
        #line 65 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cb_flip;
        
        #line default
        #line hidden
        
        
        #line 68 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lb_cuurentTeklaProfile;
        
        #line default
        #line hidden
        
        
        #line 70 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lb_currentMaterial;
        
        #line default
        #line hidden
        
        
        #line 72 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar pro_modify;
        
        #line default
        #line hidden
        
        
        #line 73 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label tx_progressbarPres;
        
        #line default
        #line hidden
        
        
        #line 76 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button tb_PickLines_Panel;
        
        #line default
        #line hidden
        
        
        #line 77 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cm_panelAtt;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Cad_to_tekla;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.w_mainWindow = ((Cad_to_tekla.MainWindow)(target));
            
            #line 10 "MainWindow.xaml"
            this.w_mainWindow.Closed += new System.EventHandler(this.Window_Closed);
            
            #line default
            #line hidden
            
            #line 10 "MainWindow.xaml"
            this.w_mainWindow.Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.tb_ref = ((System.Windows.Controls.Button)(target));
            
            #line 18 "MainWindow.xaml"
            this.tb_ref.Click += new System.Windows.RoutedEventHandler(this.tb_ref_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.tb_PickLines = ((System.Windows.Controls.Button)(target));
            
            #line 19 "MainWindow.xaml"
            this.tb_PickLines.Click += new System.Windows.RoutedEventHandler(this.tb_PickLines_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.tb_modifyModel = ((System.Windows.Controls.Button)(target));
            
            #line 20 "MainWindow.xaml"
            this.tb_modifyModel.Click += new System.Windows.RoutedEventHandler(this.tb_modifyModel_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.tb_pickProfile = ((System.Windows.Controls.Button)(target));
            return;
            case 6:
            this.cb_vl_hz = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.cm_beamAtt = ((System.Windows.Controls.ComboBox)(target));
            
            #line 27 "MainWindow.xaml"
            this.cm_beamAtt.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.cm_beamAtt_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.dt_data = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 9:
            this.Select = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 11:
            this.tb_browesRef = ((System.Windows.Controls.Button)(target));
            
            #line 58 "MainWindow.xaml"
            this.tb_browesRef.Click += new System.Windows.RoutedEventHandler(this.tb_browesRef_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.tx_refPath = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.tx_refScale = ((System.Windows.Controls.TextBox)(target));
            
            #line 60 "MainWindow.xaml"
            this.tx_refScale.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.tx_refScale_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 14:
            this.cb_flip = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 15:
            
            #line 66 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.lb_cuurentTeklaProfile = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.lb_currentMaterial = ((System.Windows.Controls.Label)(target));
            return;
            case 18:
            
            #line 71 "MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click1);
            
            #line default
            #line hidden
            return;
            case 19:
            this.pro_modify = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 20:
            this.tx_progressbarPres = ((System.Windows.Controls.Label)(target));
            return;
            case 21:
            this.tb_PickLines_Panel = ((System.Windows.Controls.Button)(target));
            
            #line 76 "MainWindow.xaml"
            this.tb_PickLines_Panel.Click += new System.Windows.RoutedEventHandler(this.tb_PickLines_Panel_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.cm_panelAtt = ((System.Windows.Controls.ComboBox)(target));
            
            #line 77 "MainWindow.xaml"
            this.cm_panelAtt.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.cm_panelAtt_SelectionChanged);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 10:
            
            #line 38 "MainWindow.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.SelcetedRadioButtom_Checked);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

